# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # whitelist
  only:
    - windows

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

environment:
  matrix:
    - BUILD_MODE: Debug
    - BUILD_MODE: Release
        # - BUILD_SHARED_LIBS: ON
        # - BUILD_SHARED_LIBS: OFF
matrix:
    fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_SHARED_LIBS=OFF ..
  - cmake --build . --config %BUILD_MODE -- /m

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - Release\testGameOfLife.exe --gtest_filter=Cpu*


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - on_build_success: false
  - on_build_failure: true