version: 1.0.{build}

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2015
clone_folder: c:\projects\GameOfLife

install:
  - echo Downloading CUDA toolkit 8
  - appveyor DownloadFile https://www.dropbox.com/s/s2ohvfp4u0f34tg/cuda.zip?dl=1
  - 7z x cuda.zip -ocuda
  - cd cuda\cuda
  - echo Installing CUDA toolkit 8
  - setup.exe -s compiler_8.0 cublas_8.0 cublas_dev_8.0 cudart_8.0 curand_8.0 curand_dev_8.0

  - echo Installing VS integration
  - copy _vs\*.* "c:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations"

  - cd ..\..

  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;%PATH%
  - set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0
  - set CUDA_PATH_V8_0=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0

  - nvcc -V

environment:
  matrix:
    - BUILD_MODE: Debug
    - BUILD_MODE: Release
    # - BUILD_SHARED_LIBS: ON
    # - BUILD_SHARED_LIBS: OFF
matrix:
    fast_finish: true

platform: x64

build_script:
  - cd c:\projects\GameOfLife
  - mkdir build
  - cd build
  - cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DBUILD_SHARED_LIBS=OFF ..
  - cmake --build . --config %BUILD_MODE% -- /m
  - cd ..

test_script:
  - build\%BUILD_MODE%\testGameOfLife.exe --gtest_filter=Cpu*

  - build\%BUILD_MODE%\gameOfLife.exe -s=7
  - build\%BUILD_MODE%\gameOfLife.exe -s=7 --threads
  
  - Measure-Command { .\build\Release\gameOfLife.exe -np -s=63 -w=500 -h=500 -i=1000 }
  - Measure-Command { .\build\Release\gameOfLife.exe -np -s=63 -w=500 -h=500 -i=1000 --threads }

notifications:
  - on_build_success: false
  - on_build_failure: true