language: c++

branches:
  only:
    - master

dist: trusty

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_clang38: &clang38
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8' ]
      packages: [ 'clang-3.8', 'libc++-dev' ]
  addons_clang39: &clang39
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9' ]
      packages: [ 'clang-3.9', 'libc++-dev' ]
  addons_clang35: &clang40
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0' ]
      packages: [ 'clang-4.0', 'libc++-dev' ]
  addons_gcc49: &gcc49
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'gcc-4.9', 'g++-4.9' ]
  addons_gcc5: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'gcc-5', 'g++-5' ]
  addons_gcc6: &gcc6
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'gcc-6', 'g++-6', 'doxygen' ]


# addons:
#   apt:
#     sources: &sources
#       - ubuntu-toolchain-r-test

# env:
#   CUDA=7.5-18
#   CUDA=8.0.44-1

matrix:
  include:
    # - os: osx
    #   osx_image: xcode6
    #   compiler: clang
    # - os: osx
    #   osx_image: xcode7
    #   compiler: clang
    # - os: osx
    #   osx_image: xcode8
    #   compiler: clang
    - os: linux
      compiler: "clang-3.8"
      env: LLVM=3.8 CXXFLAGS=-stdlib=libc++
      addons: *clang38
    - os: linux
      compiler: "clang-3.9"
      env: LLVM=3.9 CXXFLAGS=-stdlib=libc++
      addons: *clang39
    - os: linux
      compiler: "clang-4.0"
      env: LLVM=4.0 CXXFLAGS=-stdlib=libc++
      addons: *clang40
    - os: linux
      compiler: "g++-4.9"
      env: GCC=4.9
      addons: *gcc49
    - os: linux
      compiler: "g++-5"
      env: GCC=5
      addons: *gcc5
    - os: linux
      compiler: "g++-6"
      env: GCC=6
      addons: *gcc6

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
    fi

  ############################################################################
  # Setup default versions and override compiler if needed
  ############################################################################
  - if [[ "${LLVM}" == "default" ]]; then LLVM=3.8; fi
  - |
    if [[ "${LLVM}" != "" ]]; then
      # export CXX=clang++-${LLVM}
      sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${LLVM} 1
      sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${LLVM} 1
    fi
  - |
    if [[ "${GCC}" != "" ]]; then
      # export CXX=g++-${GCC}
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC} 1
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC} 1
    fi
  - ${CXX} --version

install:
  ############################################################################
  # All compiled dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

  ############################################################################
  # Install CUDA
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CUDA}" != "" ]]; then
      travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA}_amd64.deb
      travis_retry sudo dpkg -i cuda-repo-ubuntu1404_${CUDA}_amd64.deb
      travis_retry sudo apt-get update -qq
      export CUDA_APT=${CUDA:0:3}
      export CUDA_APT=${CUDA_APT/./-}
      travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}
      travis_retry sudo apt-get clean
      export CUDA_HOME=/usr/local/cuda-${CUDA:0:3}
      export LD_LIBRARY_PATH=${CUDA_HOME}/nvvm/lib64:${LD_LIBRARY_PATH}
      export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
      export PATH=${CUDA_HOME}/bin:${PATH}
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CUDA}" != "" ]]; then nvcc --version; fi;

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  ############################################################################
  # Build main simulation library and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$SHARED -DSTRICT_FLAGS=ON ..
  - cmake --build . -- -j12

  ############################################################################
  # Run CPU unit test only (GPU stuff won't work with travis)
  ############################################################################
  - ./testGameOfLife --gtest_filter=Cpu*

notifications:
  on_success: never
  on_failure: never
  # on_failure: always